# Generated by Django 3.1.8 on 2021-10-27 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contest', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=30)),
                ('language', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('time_submit', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('link_submit', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
