# Generated by Django 3.1.8 on 2021-10-17 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='', max_length=30)),
                ('participants', models.TextField(blank=True, default='{}')),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('linkcontest', models.CharField(blank=True, default='', max_length=100)),
                ('linkdatatrain', models.CharField(blank=True, default='', max_length=100)),
                ('linkdatatest', models.CharField(blank=True, default='', max_length=100)),
                ('linktester', models.CharField(blank=True, default='', max_length=100)),
                ('timeregist', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('timestart', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('timeend', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('language', models.TextField(blank=True, default='[]')),
            ],
        ),
    ]
